### PR TITLE
Update to 1.20.2

### PR DESCRIPTION
**Pull request by voximity**
This PR updates the mod to 1.20.2, which mostly dealt with changes to some of the GUI sprite stuff.

### CODE REVIEW

**Comment by AliahX** [comment]
tysm, I haven't had a lot of time to work on mixtape recently so I really appreciate it. I'll check through the pr properly soon but I had a quick check and it looks all good. tyyy <3

**Comment by spencermacca** [comment]
Just tested it, works great 👍

**For anybody who wants a build:**
https://www.dropbox.com/scl/fi/nwvczrvbn87gh7rere41a/Mixtape-1.6.1.jar?rlkey=zb3cknsphwsnjh8auk3qt5ihv&dl=0


**If you would rather build yourself:**
- Download the source code from [here](https://github.com/voximity/Mixtape/tree/1.20.2)
- Navigate to the directory in command line and run `.\gradlew build`
- The jar will output to `Mixtape-1.20.2\build\libs\Mixtape-1.6.1.jar`

**Comment by pajicadvance** [comment]
Here's a small patch that can be applied to this PR to get the mod working on 1.20.4.

[Update_to_1_20_4.patch](https://github.com/AliahX/Mixtape/files/13943815/Update_to_1_20_4.patch)

**Comment by voximity** [comment]
Since removed `.vscode` launch configs (since they had paths to things on my machine locally... not sure how I didn't notice that) and fixed the YACL dependency workarounds as YACL's author has fixed that issue.

**Comment by voximity** [comment]
> Here's a small patch that can be applied to this PR to get the mod working on 1.20.4.
> 
> [Update_to_1_20_4.patch](https://github.com/AliahX/Mixtape/files/13943815/Update_to_1_20_4.patch)

I'm not totally sure what the prospects are with this current version of the mod since the mod author seems to be working on a pretty major update, but feel free to fork this PR over and apply that for a new PR!

**Pull request merged**
